export const LOCATIONS_DB = {
  ירושלים: {
    he: 'ירושלים',
    geolexid: '537511',
    en: 'Jerusalem',
    checkboxRegions: 'checkboxRegions-2',
    source: 1056,
  },
  טבריה: {
    he: 'טבריה',
    geolexid: '537904',
    en: 'Tiberias',
    checkboxRegions: 'checkboxRegions-6',
    source: 97,
  },
  'תל אביב': {
    he: 'תל אביב',
    geolexid: '537905',
    en: 'Tel Aviv',
    checkboxRegions: 'checkboxRegions-1',
    source: 779,
  },
  נשר: {
    he: 'נשר',
    geolexid: '537906',
    en: 'Nesher',
    checkboxRegions: 'checkboxRegions-6',
    source: 549,
  },
  'כפר סבא': {
    he: 'כפר סבא',
    geolexid: '537907',
    en: 'Kfar Saba',
    checkboxRegions: 'checkboxRegions-4',
    source: 714,
  },
  מרכז: {
    he: 'מרכז',
    geolexid: '539071',
    en: 'Centre',
    checkboxRegions: 'checkboxRegions-6',
    source: 372,
  },
  אשדוד: {
    he: 'אשדוד',
    geolexid: '539073',
    en: 'Ashdod',
    checkboxRegions: 'checkboxRegions-7',
    source: 802,
  },
  חדרה: {
    he: 'חדרה',
    geolexid: '539074',
    en: 'Hadera',
    checkboxRegions: 'checkboxRegions-4',
    source: 713,
  },
  אשקלון: {
    he: 'אשקלון',
    geolexid: '539075',
    en: 'Ashkelon',
    checkboxRegions: 'checkboxRegions-5',
    source: 943,
  },
  רחובות: {
    he: 'רחובות',
    geolexid: '539076',
    en: 'Rehovot',
    checkboxRegions: 'checkboxRegions-7',
    source: 948,
  },
  'באר שבע': {
    he: 'באר שבע',
    geolexid: '539077',
    en: 'Beersheba',
    checkboxRegions: 'checkboxRegions-5',
    source: 1961,
  },
  'ראשון לציון': {
    he: 'ראשון לציון',
    geolexid: '539078',
    en: 'Rishon LeZion',
    checkboxRegions: 'checkboxRegions-1',
    source: 787,
  },
  כרמיאל: {
    he: 'כרמיאל',
    geolexid: '539079',
    en: 'Karmiel',
    checkboxRegions: 'checkboxRegions-6',
    source: 286,
  },
  נתניה: {
    he: 'נתניה',
    geolexid: '539080',
    en: 'Netanya',
    checkboxRegions: 'checkboxRegions-4',
    source: 717,
  },
  עפולה: {
    he: 'עפולה',
    geolexid: '539081',
    en: 'Afula',
    checkboxRegions: 'checkboxRegions-6',
    source: 453,
  },
  מודיעין: {
    he: 'מודיעין',
    geolexid: '539082',
    en: "Modi'in-Maccabim-Re'ut",
    checkboxRegions: 'checkboxRegions-1',
    source: 996,
  },
  'ראש העין': {
    he: 'ראש העין',
    geolexid: '539085',
    en: 'Rosh HaAyin',
    checkboxRegions: 'checkboxRegions-1',
    source: 778,
  },
  חולון: {
    he: 'חולון',
    geolexid: '539086',
    en: 'Holon',
    checkboxRegions: 'checkboxRegions-1',
    source: 783,
  },
  'בית שמש': {
    he: 'בית שמש',
    geolexid: '539087',
    en: 'Beit Shemesh',
    checkboxRegions: 'checkboxRegions-2',
    source: 1011,
  },
  יבנה: {
    he: 'יבנה',
    geolexid: '539088',
    en: 'Yavne',
    checkboxRegions: 'checkboxRegions-7',
    source: 941,
  },
  נהריה: {
    he: 'נהריה',
    geolexid: '539089',
    en: 'Nahariya',
    checkboxRegions: 'checkboxRegions-6',
    source: 412,
  },
  אילת: {
    he: 'אילת',
    geolexid: '539091',
    en: 'Eilat',
    checkboxRegions: 'checkboxRegions-3',
    source: 1978,
  },
  רעננה: {
    he: 'רעננה',
    geolexid: '539092',
    en: "Ra'anana",
    checkboxRegions: 'checkboxRegions-4',
    source: 721,
  },
  'אור יהודה': {
    he: 'אור יהודה',
    geolexid: '539093',
    en: 'Or Yehuda',
    checkboxRegions: 'checkboxRegions-1',
    source: 775,
  },
  אריאל: {
    he: 'אריאל',
    geolexid: '539094',
    en: 'Ariel',
    checkboxRegions: 'checkboxRegions-9',
    source: 1410,
  },
  חיפה: {
    he: 'חיפה',
    geolexid: '539095',
    en: 'Haifa',
    checkboxRegions: 'checkboxRegions-6',
    source: 491,
  },
  שוהם: {
    he: 'שוהם',
    geolexid: '539096',
    en: 'Shoham',
    checkboxRegions: 'checkboxRegions-1',
    source: 764,
  },
  לוד: {
    he: 'לוד',
    geolexid: '539097',
    en: 'Lod',
    checkboxRegions: 'checkboxRegions-1',
    source: 784,
  },
  'נס ציונה': {
    he: 'נס ציונה',
    geolexid: '539098',
    en: 'Ness Ziona',
    checkboxRegions: 'checkboxRegions-7',
    source: 944,
  },
  הרצליה: {
    he: 'הרצליה',
    geolexid: '539099',
    en: 'Herzliyya',
    checkboxRegions: 'checkboxRegions-4',
    source: 712,
  },
  נצרת: {
    he: 'נצרת',
    geolexid: '539100',
    en: 'Nazareth',
    checkboxRegions: 'checkboxRegions-6',
    source: 398,
  },
  'מגדל העמק': {
    he: 'מגדל העמק',
    geolexid: '539101',
    en: 'Migdal HaEmeq',
    checkboxRegions: 'checkboxRegions-6',
    source: 250,
  },
  'הוד השרון': {
    he: 'הוד השרון',
    geolexid: '539102',
    en: 'Hod HaSharon',
    checkboxRegions: 'checkboxRegions-4',
    source: 722,
  },
  רמלה: {
    he: 'רמלה',
    geolexid: '539103',
    en: 'Ramla',
    checkboxRegions: 'checkboxRegions-1',
    source: 788,
  },
  יהוד: {
    he: 'יהוד',
    geolexid: '539104',
    en: 'Yehud',
    checkboxRegions: 'checkboxRegions-1',
    source: 790,
  },
  בנימינה: {
    he: 'בנימינה',
    geolexid: '539106',
    en: 'Binyamina',
    checkboxRegions: 'checkboxRegions-6',
    source: 723,
  },
  נתיבות: {
    he: 'נתיבות',
    geolexid: '539107',
    en: 'Netivot',
    checkboxRegions: 'checkboxRegions-5',
    source: 1677,
  },
  'אור עקיבא': {
    he: 'אור עקיבא',
    geolexid: '539108',
    en: 'Or Akiva',
    checkboxRegions: 'checkboxRegions-6',
    source: 671,
  },
  'קרית גת': {
    he: 'קרית גת',
    geolexid: '539109',
    en: 'Kiryat Gat',
    checkboxRegions: 'checkboxRegions-5',
    source: 940,
  },
  שדרות: {
    he: 'שדרות',
    geolexid: '539110',
    en: 'Sderot',
    checkboxRegions: 'checkboxRegions-5',
    source: 1747,
  },
  צפת: {
    he: 'צפת',
    geolexid: '539112',
    en: 'Safed',
    checkboxRegions: 'checkboxRegions-6',
    source: 408,
  },
  ברקן: {
    he: 'ברקן',
    geolexid: '539114',
    en: 'Barkan',
    checkboxRegions: 'checkboxRegions-9',
    source: 1483,
  },
  'בת ים': {
    he: 'בת ים',
    geolexid: '539116',
    en: 'Bat-Yam',
    checkboxRegions: 'checkboxRegions-1',
    source: 781,
  },
  'קרית מלאכי': {
    he: 'קרית מלאכי',
    geolexid: '539117',
    en: "Kiryat Mal'akhi",
    checkboxRegions: 'checkboxRegions-5',
    source: 906,
  },
  ערד: {
    he: 'ערד',
    geolexid: '539118',
    en: 'Arad',
    checkboxRegions: 'checkboxRegions-5',
    source: 1843,
  },
  'בני ברק': {
    he: 'בני ברק',
    geolexid: '539119',
    en: 'Bnei Brak',
    checkboxRegions: 'checkboxRegions-1',
    source: 780,
  },
  'רמת גן': {
    he: 'רמת גן',
    geolexid: '539120',
    en: 'Ramat-Gan',
    checkboxRegions: 'checkboxRegions-1',
    source: 789,
  },
  'רמת השרון': {
    he: 'רמת השרון',
    geolexid: '539121',
    en: 'Ramat HaSharon',
    checkboxRegions: 'checkboxRegions-4',
    source: 703,
  },
  עכו: {
    he: 'עכו',
    geolexid: '539123',
    en: 'Acre',
    checkboxRegions: 'checkboxRegions-6',
    source: 405,
  },
  'גבעת שמואל': {
    he: 'גבעת שמואל',
    geolexid: '539124',
    en: "Giv'at Shmuel",
    checkboxRegions: 'checkboxRegions-1',
    source: 745,
  },
  דימונה: {
    he: 'דימונה',
    geolexid: '539125',
    en: 'Dimona',
    checkboxRegions: 'checkboxRegions-5',
    source: 1839,
  },
  'פתח תקווה': {
    he: 'פתח תקווה',
    geolexid: '539128',
    en: 'Petach Tikva',
    checkboxRegions: 'checkboxRegions-1',
    source: 786,
  },
  גדרה: {
    he: 'גדרה',
    geolexid: '539129',
    en: 'Gedera',
    checkboxRegions: 'checkboxRegions-7',
    source: 939,
  },
  אופקים: {
    he: 'אופקים',
    geolexid: '539130',
    en: 'Ofaqim',
    checkboxRegions: 'checkboxRegions-5',
    source: 1673,
  },
  גבעתיים: {
    he: 'גבעתיים',
    geolexid: '539131',
    en: 'Givatayim',
    checkboxRegions: 'checkboxRegions-1',
    source: 782,
  },
  'נוף הגליל': {
    he: 'נוף הגליל',
    geolexid: '539132',
    en: 'Nof HaGalil',
    checkboxRegions: 'checkboxRegions-6',
    source: 272,
  },
  'ראש פינה': {
    he: 'ראש פינה',
    geolexid: '539133',
    en: 'Rosh Pinna',
    checkboxRegions: 'checkboxRegions-6',
    source: 102,
  },
  'רמת ישי': {
    he: 'רמת ישי',
    geolexid: '539134',
    en: 'Ramat Yishai',
    checkboxRegions: 'checkboxRegions-6',
    source: 421,
  },
  'כוכב יאיר צור יגאל': {
    he: 'כוכב יאיר צור יגאל',
    geolexid: '539135',
    en: "Kokhav Ya'ir–Tzur Yig'al",
    checkboxRegions: 'checkboxRegions-4',
    source: 679,
  },
  'בית שאן': {
    he: 'בית שאן',
    geolexid: '539136',
    en: "Beit She'an",
    checkboxRegions: 'checkboxRegions-6',
    source: 489,
  },
  'מעלה אדומים': {
    he: 'מעלה אדומים',
    geolexid: '539140',
    en: "Ma'ale Adummim",
    checkboxRegions: 'checkboxRegions-2',
    source: 1063,
  },
  'גן יבנה': {
    he: 'גן יבנה',
    geolexid: '539141',
    en: 'Gan Yavne',
    checkboxRegions: 'checkboxRegions-7',
    source: 812,
  },
  'זכרון יעקב': {
    he: 'זכרון יעקב',
    geolexid: '539142',
    en: "Zichron Ya'aqov",
    checkboxRegions: 'checkboxRegions-6',
    source: 557,
  },
  'טירת כרמל': {
    he: 'טירת כרמל',
    geolexid: '539143',
    en: 'Tirat Carmel',
    checkboxRegions: 'checkboxRegions-6',
    source: 548,
  },
  'אבן יהודה': {
    he: 'אבן יהודה',
    geolexid: '539144',
    en: 'Even Yehuda',
    checkboxRegions: 'checkboxRegions-4',
    source: 572,
  },
  צריפין: {
    he: 'צריפין',
    geolexid: '539146',
    en: 'Tzrifin',
    checkboxRegions: 'checkboxRegions-1',
    source: 791,
  },
  קריות: {
    he: 'קריות',
    geolexid: '539148',
    en: 'Krayot',
    checkboxRegions: 'checkboxRegions-9',
    source: 1610,
  },
  'ביתר עילית': {
    he: 'ביתר עילית',
    geolexid: '539149',
    en: 'Beitar Illit',
    checkboxRegions: 'checkboxRegions-2',
    source: 1585,
  },
  'מודיעין עילית': {
    he: 'מודיעין עילית',
    geolexid: '539150',
    en: "Modi'in Illit",
    checkboxRegions: 'checkboxRegions-2',
    source: 1596,
  },
  קיסריה: {
    he: 'קיסריה',
    geolexid: '539153',
    en: 'Caesarea',
    checkboxRegions: 'checkboxRegions-6',
    source: 678,
  },
  קליה: {
    he: 'קליה',
    geolexid: '539183',
    en: 'Kalya',
    checkboxRegions: 'checkboxRegions-2',
    source: 1666,
  },
  'בית הערבה': {
    he: 'בית הערבה',
    geolexid: '539185',
    en: 'Beit HaArava',
    checkboxRegions: 'checkboxRegions-2',
    source: 1668,
  },
  'כפר האורנים': {
    he: 'כפר האורנים',
    geolexid: '539191',
    en: 'Kfar Ha-Oranim',
    checkboxRegions: 'checkboxRegions-2',
    source: 1014,
  },
  'מבוא חורון': {
    he: 'מבוא חורון',
    geolexid: '539192',
    en: 'Mevo Horon',
    checkboxRegions: 'checkboxRegions-2',
    source: 1529,
  },
  'כוכב השחר': {
    he: 'כוכב השחר',
    geolexid: '539193',
    en: 'Kohav HaShahar',
    checkboxRegions: 'checkboxRegions-2',
    source: 1404,
  },
  'גבעון החדשה': {
    he: 'גבעון החדשה',
    geolexid: '539195',
    en: 'Givon HaHadasha',
    checkboxRegions: 'checkboxRegions-2',
    source: 1473,
  },
  'מעלה שומרון': {
    he: 'מעלה שומרון',
    geolexid: '539199',
    en: 'Maale Shomron',
    checkboxRegions: 'checkboxRegions-9',
    source: 1466,
  },
  רבבה: {
    he: 'רבבה',
    geolexid: '539201',
    en: 'Revava',
    checkboxRegions: 'checkboxRegions-9',
    source: 1595,
  },
  רהט: {
    he: 'רהט',
    geolexid: '539202',
    en: 'Rahat',
    checkboxRegions: 'checkboxRegions-5',
    source: 1768,
  },
  'תל שבע': {
    he: 'תל שבע',
    geolexid: '539205',
    en: 'Tel as-Sabi',
    checkboxRegions: 'checkboxRegions-5',
    source: 1752,
  },
  ירוחם: {
    he: 'ירוחם',
    geolexid: '539207',
    en: 'Yeruham',
    checkboxRegions: 'checkboxRegions-5',
    source: 1722,
  },
  עומר: {
    he: 'עומר',
    geolexid: '539208',
    en: 'Omer',
    checkboxRegions: 'checkboxRegions-5',
    source: 1703,
  },
  מיתר: {
    he: 'מיתר',
    geolexid: '539209',
    en: 'Meitar',
    checkboxRegions: 'checkboxRegions-5',
    source: 1791,
  },
  להבים: {
    he: 'להבים',
    geolexid: '539210',
    en: 'Lehavim',
    checkboxRegions: 'checkboxRegions-5',
    source: 1001,
  },
  'מצפה רמון': {
    he: 'מצפה רמון',
    geolexid: '539211',
    en: 'Mitzpe Ramon',
    checkboxRegions: 'checkboxRegions-5',
    source: 1676,
  },
  'בית קמה': {
    he: 'בית קמה',
    geolexid: '539215',
    en: 'Beit Kama',
    checkboxRegions: 'checkboxRegions-5',
    source: 1700,
  },
  גילת: {
    he: 'גילת',
    geolexid: '539218',
    en: 'Gilat',
    checkboxRegions: 'checkboxRegions-5',
    source: 1711,
  },
  'עין הבשור': {
    he: 'עין הבשור',
    geolexid: '539219',
    en: 'Ein HaBesor',
    checkboxRegions: 'checkboxRegions-5',
    source: 1786,
  },
  חצרים: {
    he: 'חצרים',
    geolexid: '539222',
    en: 'Hatzerim',
    checkboxRegions: 'checkboxRegions-5',
    source: 1689,
  },
  'משמר הנגב': {
    he: 'משמר הנגב',
    geolexid: '539226',
    en: 'Mishmar HaNegev',
    checkboxRegions: 'checkboxRegions-5',
    source: 1687,
  },
  נבטים: {
    he: 'נבטים',
    geolexid: '539227',
    en: 'Nevatim',
    checkboxRegions: 'checkboxRegions-5',
    source: 1688,
  },
  שובל: {
    he: 'שובל',
    geolexid: '539233',
    en: 'Shoval',
    checkboxRegions: 'checkboxRegions-5',
    source: 1686,
  },
  מגן: {
    he: 'מגן',
    geolexid: '539234',
    en: 'Magen',
    checkboxRegions: 'checkboxRegions-6',
    source: 446,
  },
  'עין גדי': {
    he: 'עין גדי',
    geolexid: '539237',
    en: 'Ein Gedi',
    checkboxRegions: 'checkboxRegions-5',
    source: 1664,
  },
  צאלים: {
    he: 'צאלים',
    geolexid: '539243',
    en: 'Tzeelim',
    checkboxRegions: 'checkboxRegions-5',
    source: 1694,
  },
  דבירה: {
    he: 'דבירה',
    geolexid: '539247',
    en: 'Dvir',
    checkboxRegions: 'checkboxRegions-5',
    source: 982,
  },
  'ניר עוז': {
    he: 'ניר עוז',
    geolexid: '539266',
    en: 'Nir Oz',
    checkboxRegions: 'checkboxRegions-5',
    source: 1674,
  },
  אשלים: {
    he: 'אשלים',
    geolexid: '539284',
    en: 'Ashalim',
    checkboxRegions: 'checkboxRegions-5',
    source: 1767,
  },
  כמהין: {
    he: 'כמהין',
    geolexid: '539300',
    en: 'Kmehin',
    checkboxRegions: 'checkboxRegions-5',
    source: 1795,
  },
  'כפר מנחם': {
    he: 'כפר מנחם',
    geolexid: '539324',
    en: 'Kfar Menahem',
    checkboxRegions: 'checkboxRegions-7',
    source: 818,
  },
  'באר טוביה': {
    he: 'באר טוביה',
    geolexid: '539327',
    en: 'Beer Tuvia',
    checkboxRegions: 'checkboxRegions-5',
    source: 806,
  },
  אמונים: {
    he: 'אמונים',
    geolexid: '539328',
    en: 'Emunim',
    checkboxRegions: 'checkboxRegions-5',
    source: 882,
  },
  שחר: {
    he: 'שחר',
    geolexid: '539338',
    en: 'Shahar',
    checkboxRegions: 'checkboxRegions-5',
    source: 792,
  },
  דורות: {
    he: 'דורות',
    geolexid: '539343',
    en: 'Dorot',
    checkboxRegions: 'checkboxRegions-5',
    source: 1680,
  },
  לכיש: {
    he: 'לכיש',
    geolexid: '539344',
    en: 'Lachish',
    checkboxRegions: 'checkboxRegions-5',
    source: 954,
  },
  'ברור חיל': {
    he: 'ברור חיל',
    geolexid: '539345',
    en: 'Bror Hayil',
    checkboxRegions: 'checkboxRegions-5',
    source: 835,
  },
  'כפר אחים': {
    he: 'כפר אחים',
    geolexid: '539348',
    en: 'Kfar Ahim',
    checkboxRegions: 'checkboxRegions-7',
    source: 858,
  },
  שפיר: {
    he: 'שפיר',
    geolexid: '539349',
    en: 'Shafir',
    checkboxRegions: 'checkboxRegions-5',
    source: 859,
  },
  'יד מרדכי': {
    he: 'יד מרדכי',
    geolexid: '539350',
    en: 'Yad Mordechai',
    checkboxRegions: 'checkboxRegions-5',
    source: 828,
  },
  נגבה: {
    he: 'נגבה',
    geolexid: '539354',
    en: 'Negba',
    checkboxRegions: 'checkboxRegions-5',
    source: 823,
  },
  סגולה: {
    he: 'סגולה',
    geolexid: '539355',
    en: 'Sgula',
    checkboxRegions: 'checkboxRegions-5',
    source: 936,
  },
  'נחל עוז': {
    he: 'נחל עוז',
    geolexid: '539377',
    en: 'Nahal Oz',
    checkboxRegions: 'checkboxRegions-5',
    source: 1724,
  },
  מבקיעים: {
    he: 'מבקיעים',
    geolexid: '539378',
    en: 'Mavkiim',
    checkboxRegions: 'checkboxRegions-5',
    source: 844,
  },
  גברעם: {
    he: 'גברעם',
    geolexid: '539379',
    en: 'Gvaram',
    checkboxRegions: 'checkboxRegions-5',
    source: 826,
  },
  אזור: {
    he: 'אזור',
    geolexid: '539386',
    en: 'Azor',
    checkboxRegions: 'checkboxRegions-6',
    source: 395,
  },
  'כפר שמריהו': {
    he: 'כפר שמריהו',
    geolexid: '539387',
    en: 'Kfar Shmaryahu',
    checkboxRegions: 'checkboxRegions-4',
    source: 603,
  },
  'מזכרת בתיה': {
    he: 'מזכרת בתיה',
    geolexid: '539389',
    en: 'Mazkeret Batya',
    checkboxRegions: 'checkboxRegions-7',
    source: 794,
  },
  'יד בנימין': {
    he: 'יד בנימין',
    geolexid: '539390',
    en: 'Yad Binyamin',
    checkboxRegions: 'checkboxRegions-7',
    source: 845,
  },
  'בני ראם': {
    he: 'בני ראם',
    geolexid: '539395',
    en: 'Bnei Reem',
    checkboxRegions: 'checkboxRegions-7',
    source: 848,
  },
  עשרת: {
    he: 'עשרת',
    geolexid: '539396',
    en: 'Aseret',
    checkboxRegions: 'checkboxRegions-7',
    source: 849,
  },
  'קבוצת יבנה': {
    he: 'קבוצת יבנה',
    geolexid: '539399',
    en: 'Kvutzat Yavne',
    checkboxRegions: 'checkboxRegions-7',
    source: 825,
  },
  'בית רבן': {
    he: 'בית רבן',
    geolexid: '539402',
    en: 'Givat Washington',
    checkboxRegions: 'checkboxRegions-7',
    source: 899,
  },
  מישר: {
    he: 'מישר',
    geolexid: '539403',
    en: 'Meishar',
    checkboxRegions: 'checkboxRegions-7',
    source: 867,
  },
  'בני דרום': {
    he: 'בני דרום',
    geolexid: '539411',
    en: 'Bnei Darom',
    checkboxRegions: 'checkboxRegions-7',
    source: 850,
  },
  'גן הדרום': {
    he: 'גן הדרום',
    geolexid: '539414',
    en: 'Gan HaDarom',
    checkboxRegions: 'checkboxRegions-7',
    source: 909,
  },
  נטעים: {
    he: 'נטעים',
    geolexid: '539415',
    en: 'Netaim',
    checkboxRegions: 'checkboxRegions-7',
    source: 813,
  },
  פלמחים: {
    he: 'פלמחים',
    geolexid: '539417',
    en: 'Palmachim',
    checkboxRegions: 'checkboxRegions-7',
    source: 852,
  },
  'באר יעקב': {
    he: 'באר יעקב',
    geolexid: '539421',
    en: 'Beer Yaakov',
    checkboxRegions: 'checkboxRegions-7',
    source: 776,
  },
  'בית דגן': {
    he: 'בית דגן',
    geolexid: '539422',
    en: 'Beit Dagan',
    checkboxRegions: 'checkboxRegions-1',
    source: 735,
  },
  'כרמי יוסף': {
    he: 'כרמי יוסף',
    geolexid: '539425',
    en: 'Karmei Yosef',
    checkboxRegions: 'checkboxRegions-2',
    source: 999,
  },
  'ניר צבי': {
    he: 'ניר צבי',
    geolexid: '539429',
    en: 'Nir Tzvi',
    checkboxRegions: 'checkboxRegions-1',
    source: 731,
  },
  מצליח: {
    he: 'מצליח',
    geolexid: '539430',
    en: 'Matsliah',
    checkboxRegions: 'checkboxRegions-7',
    source: 874,
  },
  עזריה: {
    he: 'עזריה',
    geolexid: '539434',
    en: 'Azaria',
    checkboxRegions: 'checkboxRegions-2',
    source: 863,
  },
  ישרש: {
    he: 'ישרש',
    geolexid: '539437',
    en: 'Yashresh',
    checkboxRegions: 'checkboxRegions-7',
    source: 896,
  },
  'בית נחמיה': {
    he: 'בית נחמיה',
    geolexid: '539438',
    en: 'Beit Nehemia',
    checkboxRegions: 'checkboxRegions-1',
    source: 752,
  },
  יגל: {
    he: 'יגל',
    geolexid: '539440',
    en: 'Yagel',
    checkboxRegions: 'checkboxRegions-1',
    source: 755,
  },
  'משמר השבעה': {
    he: 'משמר השבעה',
    geolexid: '539441',
    en: 'Mishmar HaShiva',
    checkboxRegions: 'checkboxRegions-1',
    source: 750,
  },
  פתחיה: {
    he: 'פתחיה',
    geolexid: '539442',
    en: 'Petahia',
    checkboxRegions: 'checkboxRegions-2',
    source: 898,
  },
  'כפר טרומן': {
    he: 'כפר טרומן',
    geolexid: '539443',
    en: 'Kfar Truman',
    checkboxRegions: 'checkboxRegions-1',
    source: 744,
  },
  'נצר סרני': {
    he: 'נצר סרני',
    geolexid: '539445',
    en: 'Netzer Sereni',
    checkboxRegions: 'checkboxRegions-7',
    source: 836,
  },
  גנות: {
    he: 'גנות',
    geolexid: '539446',
    en: 'Ganot',
    checkboxRegions: 'checkboxRegions-4',
    source: 631,
  },
  שילת: {
    he: 'שילת',
    geolexid: '539452',
    en: 'Shilat',
    checkboxRegions: 'checkboxRegions-2',
    source: 994,
  },
  'משמר דוד': {
    he: 'משמר דוד',
    geolexid: '539457',
    en: 'Mishmar David',
    checkboxRegions: 'checkboxRegions-2',
    source: 965,
  },
  אלעד: {
    he: 'אלעד',
    geolexid: '539459',
    en: 'Elad',
    checkboxRegions: 'checkboxRegions-1',
    source: 765,
  },
  'גני תקווה': {
    he: 'גני תקווה',
    geolexid: '539460',
    en: 'Ganei Tikva',
    checkboxRegions: 'checkboxRegions-1',
    source: 727,
  },
  סביון: {
    he: 'סביון',
    geolexid: '539462',
    en: 'Savyon',
    checkboxRegions: 'checkboxRegions-1',
    source: 737,
  },
  ברקת: {
    he: 'ברקת',
    geolexid: '539464',
    en: 'Bareket',
    checkboxRegions: 'checkboxRegions-1',
    source: 774,
  },
  נחלים: {
    he: 'נחלים',
    geolexid: '539466',
    en: 'Nehalim',
    checkboxRegions: 'checkboxRegions-1',
    source: 733,
  },
  'שדה ורבורג': {
    he: 'שדה ורבורג',
    geolexid: '539467',
    en: 'Sde Warburg',
    checkboxRegions: 'checkboxRegions-4',
    source: 605,
  },
  מגשימים: {
    he: 'מגשימים',
    geolexid: '539473',
    en: 'Magshimim',
    checkboxRegions: 'checkboxRegions-1',
    source: 749,
  },
  'בארות יצחק': {
    he: 'בארות יצחק',
    geolexid: '539482',
    en: 'Beerot Yitzhak',
    checkboxRegions: 'checkboxRegions-1',
    source: 734,
  },
  נחשונים: {
    he: 'נחשונים',
    geolexid: '539485',
    en: 'Nahshonim',
    checkboxRegions: 'checkboxRegions-1',
    source: 747,
  },
  'צור יצחק': {
    he: 'צור יצחק',
    geolexid: '539486',
    en: 'Tzur Yitzhak',
    checkboxRegions: 'checkboxRegions-4',
    source: 686,
  },
  'צור נתן': {
    he: 'צור נתן',
    geolexid: '539488',
    en: 'Tzur Natan',
    checkboxRegions: 'checkboxRegions-4',
    source: 677,
  },
  טירה: {
    he: 'טירה',
    geolexid: '539490',
    en: 'Tira',
    checkboxRegions: 'checkboxRegions-4',
    source: 704,
  },
  'כפר יונה': {
    he: 'כפר יונה',
    geolexid: '539491',
    en: 'Kfar Yona',
    checkboxRegions: 'checkboxRegions-4',
    source: 567,
  },
  'תל מונד': {
    he: 'תל מונד',
    geolexid: '539492',
    en: 'Tel Mond',
    checkboxRegions: 'checkboxRegions-4',
    source: 563,
  },
  'שער אפרים': {
    he: 'שער אפרים',
    geolexid: '539500',
    en: 'Shaar Efraim',
    checkboxRegions: 'checkboxRegions-4',
    source: 640,
  },
  'בני ציון': {
    he: 'בני ציון',
    geolexid: '539503',
    en: 'Bnei Zion',
    checkboxRegions: 'checkboxRegions-4',
    source: 625,
  },
  רשפון: {
    he: 'רשפון',
    geolexid: '539504',
    en: 'Rishpon',
    checkboxRegions: 'checkboxRegions-4',
    source: 601,
  },
  אודים: {
    he: 'אודים',
    geolexid: '539505',
    en: 'Udim',
    checkboxRegions: 'checkboxRegions-4',
    source: 629,
  },
  'בני דרור': {
    he: 'בני דרור',
    geolexid: '539506',
    en: 'Bnei Dror',
    checkboxRegions: 'checkboxRegions-4',
    source: 620,
  },
  'עין ורד': {
    he: 'עין ורד',
    geolexid: '539507',
    en: 'Ein Vered',
    checkboxRegions: 'checkboxRegions-4',
    source: 564,
  },
  'כפר נטר': {
    he: 'כפר נטר',
    geolexid: '539509',
    en: 'Kfar Netter',
    checkboxRegions: 'checkboxRegions-4',
    source: 609,
  },
  שפיים: {
    he: 'שפיים',
    geolexid: '539510',
    en: 'Shefayim',
    checkboxRegions: 'checkboxRegions-4',
    source: 597,
  },
  בצרה: {
    he: 'בצרה',
    geolexid: '539511',
    en: 'Batzra',
    checkboxRegions: 'checkboxRegions-4',
    source: 622,
  },
  משמרת: {
    he: 'משמרת',
    geolexid: '539514',
    en: 'Mishmeret',
    checkboxRegions: 'checkboxRegions-4',
    source: 628,
  },
  'בית יהושע': {
    he: 'בית יהושע',
    geolexid: '539518',
    en: 'Beit Yehoshua',
    checkboxRegions: 'checkboxRegions-4',
    source: 607,
  },
  תנובות: {
    he: 'תנובות',
    geolexid: '539525',
    en: 'Tnuvot',
    checkboxRegions: 'checkboxRegions-4',
    source: 694,
  },
  'תל יצחק': {
    he: 'תל יצחק',
    geolexid: '539530',
    en: 'Tel Yitzhak',
    checkboxRegions: 'checkboxRegions-4',
    source: 606,
  },
  יקום: {
    he: 'יקום',
    geolexid: '539532',
    en: 'Yakum',
    checkboxRegions: 'checkboxRegions-4',
    source: 624,
  },
  'כפר יעבץ': {
    he: 'כפר יעבץ',
    geolexid: '539538',
    en: 'Kfar Yavetz',
    checkboxRegions: 'checkboxRegions-4',
    source: 568,
  },
  'משמר השרון': {
    he: 'משמר השרון',
    geolexid: '539542',
    en: 'Mishmar HaSharon kibbutz',
    checkboxRegions: 'checkboxRegions-4',
    source: 581,
  },
  'בית ינאי': {
    he: 'בית ינאי',
    geolexid: '539545',
    en: 'Beit Yanai',
    checkboxRegions: 'checkboxRegions-4',
    source: 585,
  },
  'כפר קרע': {
    he: 'כפר קרע',
    geolexid: '539555',
    en: 'Kafr Qara',
    checkboxRegions: 'checkboxRegions-6',
    source: 526,
  },
  עתלית: {
    he: 'עתלית',
    geolexid: '539557',
    en: 'Atlit',
    checkboxRegions: 'checkboxRegions-6',
    source: 497,
  },
  'מעגן מיכאל': {
    he: 'מעגן מיכאל',
    geolexid: '539558',
    en: 'Maagan Michael',
    checkboxRegions: 'checkboxRegions-6',
    source: 533,
  },
  'גן שמואל': {
    he: 'גן שמואל',
    geolexid: '539565',
    en: 'Gan Shmuel',
    checkboxRegions: 'checkboxRegions-6',
    source: 559,
  },
  'בית חנניה': {
    he: 'בית חנניה',
    geolexid: '539566',
    en: 'Beit Hanania',
    checkboxRegions: 'checkboxRegions-6',
    source: 654,
  },
  מגל: {
    he: 'מגל',
    geolexid: '539568',
    en: 'Magal',
    checkboxRegions: 'checkboxRegions-4',
    source: 616,
  },
  'שדה יצחק': {
    he: 'שדה יצחק',
    geolexid: '539572',
    en: 'Sde Yitzhak',
    checkboxRegions: 'checkboxRegions-4',
    source: 696,
  },
  'עין עירון': {
    he: 'עין עירון',
    geolexid: '539580',
    en: 'Ein Iron',
    checkboxRegions: 'checkboxRegions-6',
    source: 594,
  },
  מצר: {
    he: 'מצר',
    geolexid: '539585',
    en: 'Metzer',
    checkboxRegions: 'checkboxRegions-6',
    source: 638,
  },
  עספיא: {
    he: 'עספיא',
    geolexid: '539598',
    en: 'Isfiya',
    checkboxRegions: 'checkboxRegions-6',
    source: 519,
  },
  רכסים: {
    he: 'רכסים',
    geolexid: '539599',
    en: 'Rekhasim',
    checkboxRegions: 'checkboxRegions-6',
    source: 257,
  },
  אבטין: {
    he: 'אבטין',
    geolexid: '539601',
    en: 'Ibtin',
    checkboxRegions: 'checkboxRegions-6',
    source: 227,
  },
  'רמת יוחנן': {
    he: 'רמת יוחנן',
    geolexid: '539603',
    en: 'Ramat Yohanan',
    checkboxRegions: 'checkboxRegions-6',
    source: 114,
  },
  'כפר ביאליק': {
    he: 'כפר ביאליק',
    geolexid: '539604',
    en: 'Kfar Bialik',
    checkboxRegions: 'checkboxRegions-6',
    source: 116,
  },
  אושה: {
    he: 'אושה',
    geolexid: '539606',
    en: 'Usha',
    checkboxRegions: 'checkboxRegions-6',
    source: 121,
  },
  'כפר גלים': {
    he: 'כפר גלים',
    geolexid: '539609',
    en: 'Kfar Galim',
    checkboxRegions: 'checkboxRegions-6',
    source: 513,
  },
  קצרין: {
    he: 'קצרין',
    geolexid: '539611',
    en: 'Qatsrin',
    checkboxRegions: 'checkboxRegions-6',
    source: 27,
  },
  רמות: {
    he: 'רמות',
    geolexid: '539622',
    en: 'Ramot',
    checkboxRegions: 'checkboxRegions-6',
    source: 39,
  },
  ריינה: {
    he: 'ריינה',
    geolexid: '539637',
    en: 'Reineh',
    checkboxRegions: 'checkboxRegions-6',
    source: 203,
  },
  שפרעם: {
    he: 'שפרעם',
    geolexid: '539644',
    en: 'Shefa-Amr',
    checkboxRegions: 'checkboxRegions-6',
    source: 410,
  },
  טמרה: {
    he: 'טמרה',
    geolexid: '539645',
    en: 'Tamra',
    checkboxRegions: 'checkboxRegions-6',
    source: 411,
  },
  ירכא: {
    he: 'ירכא',
    geolexid: '539647',
    en: 'Yarka',
    checkboxRegions: 'checkboxRegions-6',
    source: 174,
  },
  שלומי: {
    he: 'שלומי',
    geolexid: '539652',
    en: 'Shlomi',
    checkboxRegions: 'checkboxRegions-6',
    source: 245,
  },
  'כפר ורדים': {
    he: 'כפר ורדים',
    geolexid: '539654',
    en: 'Kfar Vradim',
    checkboxRegions: 'checkboxRegions-6',
    source: 342,
  },
  אילון: {
    he: 'אילון',
    geolexid: '539668',
    en: 'Eilon',
    checkboxRegions: 'checkboxRegions-6',
    source: 128,
  },
  רגבה: {
    he: 'רגבה',
    geolexid: '539669',
    en: 'Regba',
    checkboxRegions: 'checkboxRegions-6',
    source: 148,
  },
  רקפת: {
    he: 'רקפת',
    geolexid: '539674',
    en: 'Rakefet',
    checkboxRegions: 'checkboxRegions-6',
    source: 331,
  },
  אחיהוד: {
    he: 'אחיהוד',
    geolexid: '539677',
    en: 'Ahihud',
    checkboxRegions: 'checkboxRegions-6',
    source: 241,
  },
  'כפר מסריק': {
    he: 'כפר מסריק',
    geolexid: '539680',
    en: 'Kfar Masaryk',
    checkboxRegions: 'checkboxRegions-6',
    source: 129,
  },
  עמקה: {
    he: 'עמקה',
    geolexid: '539688',
    en: 'Amka',
    checkboxRegions: 'checkboxRegions-6',
    source: 236,
  },
  אשחר: {
    he: 'אשחר',
    geolexid: '539692',
    en: 'Eshhar',
    checkboxRegions: 'checkboxRegions-6',
    source: 306,
  },
  'בית העמק': {
    he: 'בית העמק',
    geolexid: '539696',
    en: 'Beit HaEmek',
    checkboxRegions: 'checkboxRegions-6',
    source: 209,
  },
  'בסמת טבעון': {
    he: 'בסמת טבעון',
    geolexid: '539733',
    en: 'Basmat Tabun',
    checkboxRegions: 'checkboxRegions-6',
    source: 259,
  },
  שמשית: {
    he: 'שמשית',
    geolexid: '539735',
    en: 'Shimshit',
    checkboxRegions: 'checkboxRegions-6',
    source: 365,
  },
  'גן נר': {
    he: 'גן נר',
    geolexid: '539736',
    en: 'Gan Ner',
    checkboxRegions: 'checkboxRegions-6',
    source: 480,
  },
  'תל עדשים': {
    he: 'תל עדשים',
    geolexid: '539742',
    en: 'Tel Adashim',
    checkboxRegions: 'checkboxRegions-6',
    source: 417,
  },
  'שדה יעקב': {
    he: 'שדה יעקב',
    geolexid: '539743',
    en: 'Sde Yaaqov',
    checkboxRegions: 'checkboxRegions-6',
    source: 429,
  },
  'משמר העמק': {
    he: 'משמר העמק',
    geolexid: '539744',
    en: 'Mishmar HaEmek',
    checkboxRegions: 'checkboxRegions-6',
    source: 500,
  },
  הרדוף: {
    he: 'הרדוף',
    geolexid: '539745',
    en: 'Harduf',
    checkboxRegions: 'checkboxRegions-6',
    source: 338,
  },
  'רמות מנשה': {
    he: 'רמות מנשה',
    geolexid: '539752',
    en: 'Ramot Menashe',
    checkboxRegions: 'checkboxRegions-6',
    source: 517,
  },
  'בית לחם הגלילית': {
    he: 'בית לחם הגלילית',
    geolexid: '539757',
    en: 'Bethlehem of Galilee',
    checkboxRegions: 'checkboxRegions-6',
    source: 151,
  },
  'אלוני אבא': {
    he: 'אלוני אבא',
    geolexid: '539758',
    en: 'Alonei Abba',
    checkboxRegions: 'checkboxRegions-6',
    source: 150,
  },
  'עין העמק': {
    he: 'עין העמק',
    geolexid: '539763',
    en: 'Ein HaEmek',
    checkboxRegions: 'checkboxRegions-6',
    source: 510,
  },
  מזרע: {
    he: 'מזרע',
    geolexid: '539766',
    en: 'Mizra',
    checkboxRegions: 'checkboxRegions-6',
    source: 418,
  },
  גבע: {
    he: 'גבע',
    geolexid: '539769',
    en: 'Geva',
    checkboxRegions: 'checkboxRegions-6',
    source: 458,
  },
  יזרעאל: {
    he: 'יזרעאל',
    geolexid: '539775',
    en: 'Yizreel',
    checkboxRegions: 'checkboxRegions-6',
    source: 438,
  },
  'תל יוסף': {
    he: 'תל יוסף',
    geolexid: '539779',
    en: 'Tel Yosef',
    checkboxRegions: 'checkboxRegions-6',
    source: 456,
  },
  אלונים: {
    he: 'אלונים',
    geolexid: '539784',
    en: 'Alonim',
    checkboxRegions: 'checkboxRegions-6',
    source: 125,
  },
  'כפר ברוך': {
    he: 'כפר ברוך',
    geolexid: '539792',
    en: 'Kfar Baruch',
    checkboxRegions: 'checkboxRegions-6',
    source: 423,
  },
  מלאה: {
    he: 'מלאה',
    geolexid: '539801',
    en: 'Mlea',
    checkboxRegions: 'checkboxRegions-6',
    source: 432,
  },
  יעל: {
    he: 'יעל',
    geolexid: '539810',
    en: 'Merkaz Yael',
    checkboxRegions: 'checkboxRegions-6',
    source: 445,
  },
  יבנאל: {
    he: 'יבנאל',
    geolexid: '539811',
    en: 'Yavneel',
    checkboxRegions: 'checkboxRegions-6',
    source: 104,
  },
  'כפר תבור': {
    he: 'כפר תבור',
    geolexid: '539813',
    en: 'Kfar Tavor',
    checkboxRegions: 'checkboxRegions-6',
    source: 105,
  },
  'גבעת אבני': {
    he: 'גבעת אבני',
    geolexid: '539814',
    en: 'Givat Avni',
    checkboxRegions: 'checkboxRegions-6',
    source: 349,
  },
  אפיקים: {
    he: 'אפיקים',
    geolexid: '539815',
    en: 'Afikim',
    checkboxRegions: 'checkboxRegions-6',
    source: 50,
  },
  מגדל: {
    he: 'מגדל',
    geolexid: '539816',
    en: 'Migdal',
    checkboxRegions: 'checkboxRegions-6',
    source: 109,
  },
  הזורעים: {
    he: 'הזורעים',
    geolexid: '539819',
    en: 'HaZorim',
    checkboxRegions: 'checkboxRegions-6',
    source: 131,
  },
  לביא: {
    he: 'לביא',
    geolexid: '539821',
    en: 'Lavi',
    checkboxRegions: 'checkboxRegions-6',
    source: 215,
  },
  מעגן: {
    he: 'מעגן',
    geolexid: '539836',
    en: 'Maagan',
    checkboxRegions: 'checkboxRegions-6',
    source: 77,
  },
  'חצור הגלילית': {
    he: 'חצור הגלילית',
    geolexid: '539849',
    en: 'Hatzor HaGlilit',
    checkboxRegions: 'checkboxRegions-6',
    source: 382,
  },
  מירון: {
    he: 'מירון',
    geolexid: '539852',
    en: 'Meron',
    checkboxRegions: 'checkboxRegions-6',
    source: 222,
  },
  שמיר: {
    he: 'שמיר',
    geolexid: '539855',
    en: 'Shamir',
    checkboxRegions: 'checkboxRegions-6',
    source: 71,
  },
  'כפר הנשיא': {
    he: 'כפר הנשיא',
    geolexid: '539857',
    en: 'Kfar HaNassi',
    checkboxRegions: 'checkboxRegions-6',
    source: 75,
  },
  עמיר: {
    he: 'עמיר',
    geolexid: '539869',
    en: 'Amir',
    checkboxRegions: 'checkboxRegions-6',
    source: 64,
  },
  ברעם: {
    he: 'ברעם',
    geolexid: '539870',
    en: 'Baram',
    checkboxRegions: 'checkboxRegions-6',
    source: 231,
  },
  עמיעד: {
    he: 'עמיעד',
    geolexid: '539886',
    en: 'Amiad',
    checkboxRegions: 'checkboxRegions-6',
    source: 146,
  },
  'משגב עם': {
    he: 'משגב עם',
    geolexid: '539893',
    en: 'Misgav Am',
    checkboxRegions: 'checkboxRegions-6',
    source: 145,
  },
  מנרה: {
    he: 'מנרה',
    geolexid: '539895',
    en: 'Manara',
    checkboxRegions: 'checkboxRegions-6',
    source: 137,
  },
  'מבשרת ציון': {
    he: 'מבשרת ציון',
    geolexid: '539900',
    en: 'Mevaseret Zion',
    checkboxRegions: 'checkboxRegions-2',
    source: 1043,
  },
  'צור הדסה': {
    he: 'צור הדסה',
    geolexid: '539901',
    en: 'Tzur Hadassah',
    checkboxRegions: 'checkboxRegions-2',
    source: 1047,
  },
  'עין נקובא': {
    he: 'עין נקובא',
    geolexid: '539903',
    en: 'Ein Naqquba',
    checkboxRegions: 'checkboxRegions-2',
    source: 1026,
  },
  'טל שחר': {
    he: 'טל שחר',
    geolexid: '539906',
    en: 'Tal Shahar',
    checkboxRegions: 'checkboxRegions-2',
    source: 962,
  },
  אשתאול: {
    he: 'אשתאול',
    geolexid: '539907',
    en: 'Eshtaol',
    checkboxRegions: 'checkboxRegions-2',
    source: 971,
  },
  'נס הרים': {
    he: 'נס הרים',
    geolexid: '539913',
    en: 'Nes Harim',
    checkboxRegions: 'checkboxRegions-2',
    source: 1040,
  },
  אדרת: {
    he: 'אדרת',
    geolexid: '539915',
    en: 'Aderet',
    checkboxRegions: 'checkboxRegions-2',
    source: 992,
  },
  שורש: {
    he: 'שורש',
    geolexid: '539917',
    en: 'Shoresh',
    checkboxRegions: 'checkboxRegions-6',
    source: 334,
  },
  שואבה: {
    he: 'שואבה',
    geolexid: '539919',
    en: 'Shoeva',
    checkboxRegions: 'checkboxRegions-2',
    source: 1029,
  },
  צובה: {
    he: 'צובה',
    geolexid: '539922',
    en: 'Tzova',
    checkboxRegions: 'checkboxRegions-2',
    source: 1023,
  },
  'בית נקופה': {
    he: 'בית נקופה',
    geolexid: '539923',
    en: 'Beit Nekofa',
    checkboxRegions: 'checkboxRegions-2',
    source: 1027,
  },
  'רמת רזיאל': {
    he: 'רמת רזיאל',
    geolexid: '539924',
    en: 'Ramat Raziel',
    checkboxRegions: 'checkboxRegions-2',
    source: 1022,
  },
  'נווה אילן': {
    he: 'נווה אילן',
    geolexid: '539928',
    en: 'Neve Ilan',
    checkboxRegions: 'checkboxRegions-2',
    source: 1020,
  },
  נחם: {
    he: 'נחם',
    geolexid: '539930',
    en: 'Naham',
    checkboxRegions: 'checkboxRegions-2',
    source: 1037,
  },
  'רמת רחל': {
    he: 'רמת רחל',
    geolexid: '539932',
    en: 'Ramat Rachel',
    checkboxRegions: 'checkboxRegions-2',
    source: 1017,
  },
  מחסיה: {
    he: 'מחסיה',
    geolexid: '539935',
    en: 'Mahseya',
    checkboxRegions: 'checkboxRegions-2',
    source: 1032,
  },
  לוזית: {
    he: 'לוזית',
    geolexid: '539938',
    en: 'Luzit',
    checkboxRegions: 'checkboxRegions-5',
    source: 957,
  },
  'שדות מיכה': {
    he: 'שדות מיכה',
    geolexid: '539939',
    en: 'Sdot Micha',
    checkboxRegions: 'checkboxRegions-2',
    source: 955,
  },
  צפרירים: {
    he: 'צפרירים',
    geolexid: '539942',
    en: 'Tzafririm',
    checkboxRegions: 'checkboxRegions-2',
    source: 990,
  },
  נחושה: {
    he: 'נחושה',
    geolexid: '539943',
    en: 'Nehusha',
    checkboxRegions: 'checkboxRegions-2',
    source: 958,
  },
  מחולה: {
    he: 'מחולה',
    geolexid: '539977',
    en: 'Mehola',
    checkboxRegions: 'checkboxRegions-9',
    source: 1432,
  },
  גיתית: {
    he: 'גיתית',
    geolexid: '539978',
    en: 'Gitit',
    checkboxRegions: 'checkboxRegions-9',
    source: 1444,
  },
  תומר: {
    he: 'תומר',
    geolexid: '539979',
    en: 'Tomer',
    checkboxRegions: 'checkboxRegions-9',
    source: 1400,
  },
  פצאל: {
    he: 'פצאל',
    geolexid: '539980',
    en: "Fatsa'el",
    checkboxRegions: 'checkboxRegions-9',
    source: 1446,
  },
  בקעות: {
    he: 'בקעות',
    geolexid: '539986',
    en: 'Bekaot',
    checkboxRegions: 'checkboxRegions-9',
    source: 1443,
  },
  יפית: {
    he: 'יפית',
    geolexid: '539992',
    en: 'Yafit',
    checkboxRegions: 'checkboxRegions-9',
    source: 1406,
  },
  חמרה: {
    he: 'חמרה',
    geolexid: '539995',
    en: 'Hamra',
    checkboxRegions: 'checkboxRegions-9',
    source: 1441,
  },
  רותם: {
    he: 'רותם',
    geolexid: '539996',
    en: 'Rotem',
    checkboxRegions: 'checkboxRegions-9',
    source: 1586,
  },
  'גבעת זאב': {
    he: 'גבעת זאב',
    geolexid: '539998',
    en: 'Givat Zeev',
    checkboxRegions: 'checkboxRegions-2',
    source: 1544,
  },
  'כוכב יעקב': {
    he: 'כוכב יעקב',
    geolexid: '539999',
    en: 'Kokhav Yaakov',
    checkboxRegions: 'checkboxRegions-2',
    source: 1584,
  },
  'בית אל': {
    he: 'בית אל',
    geolexid: '540000',
    en: 'Beit El',
    checkboxRegions: 'checkboxRegions-6',
    source: 461,
  },
  'גבע בנימין': {
    he: 'גבע בנימין',
    geolexid: '540001',
    en: 'Geva Binyamin',
    checkboxRegions: 'checkboxRegions-2',
    source: 1569,
  },
  'בית אריה': {
    he: 'בית אריה',
    geolexid: '540002',
    en: 'Beit Aryeh-Ofarim',
    checkboxRegions: 'checkboxRegions-9',
    source: 1481,
  },
  עפרה: {
    he: 'עפרה',
    geolexid: '540003',
    en: 'Ofra',
    checkboxRegions: 'checkboxRegions-2',
    source: 1447,
  },
  'כפר אדומים': {
    he: 'כפר אדומים',
    geolexid: '540004',
    en: 'Kfar Adumim',
    checkboxRegions: 'checkboxRegions-2',
    source: 1467,
  },
  שילה: {
    he: 'שילה',
    geolexid: '540005',
    en: 'Shiloh',
    checkboxRegions: 'checkboxRegions-9',
    source: 1471,
  },
  פסגות: {
    he: 'פסגות',
    geolexid: '540006',
    en: 'Psagot',
    checkboxRegions: 'checkboxRegions-2',
    source: 1488,
  },
  'מעלה מכמש': {
    he: 'מעלה מכמש',
    geolexid: '540007',
    en: 'Maale Michmash',
    checkboxRegions: 'checkboxRegions-2',
    source: 1480,
  },
  רימונים: {
    he: 'רימונים',
    geolexid: '540013',
    en: 'Rimonim',
    checkboxRegions: 'checkboxRegions-2',
    source: 1405,
  },
  'אלפי מנשה': {
    he: 'אלפי מנשה',
    geolexid: '540015',
    en: 'Alfei Menashe',
    checkboxRegions: 'checkboxRegions-9',
    source: 1561,
  },
  'קרני שומרון': {
    he: 'קרני שומרון',
    geolexid: '540016',
    en: 'Karnei Shomron',
    checkboxRegions: 'checkboxRegions-9',
    source: 1470,
  },
  אורנית: {
    he: 'אורנית',
    geolexid: '540017',
    en: 'Oranit',
    checkboxRegions: 'checkboxRegions-9',
    source: 1567,
  },
  'שערי תקווה': {
    he: 'שערי תקווה',
    geolexid: '540018',
    en: 'Shaarei Tikva',
    checkboxRegions: 'checkboxRegions-9',
    source: 1537,
  },
  קדומים: {
    he: 'קדומים',
    geolexid: '540019',
    en: 'Kdumim',
    checkboxRegions: 'checkboxRegions-9',
    source: 1399,
  },
  אלקנה: {
    he: 'אלקנה',
    geolexid: '540020',
    en: 'Elkana',
    checkboxRegions: 'checkboxRegions-9',
    source: 1401,
  },
  עמנואל: {
    he: 'עמנואל',
    geolexid: '540021',
    en: 'Immanuel',
    checkboxRegions: 'checkboxRegions-9',
    source: 1489,
  },
  יקיר: {
    he: 'יקיר',
    geolexid: '540023',
    en: 'Yakir',
    checkboxRegions: 'checkboxRegions-9',
    source: 1475,
  },
  צופים: {
    he: 'צופים',
    geolexid: '540024',
    en: 'Zufim',
    checkboxRegions: 'checkboxRegions-9',
    source: 1592,
  },
  סלעית: {
    he: 'סלעית',
    geolexid: '540029',
    en: 'Salit',
    checkboxRegions: 'checkboxRegions-9',
    source: 1407,
  },
  ברכה: {
    he: 'ברכה',
    geolexid: '540033',
    en: 'Har Brakha',
    checkboxRegions: 'checkboxRegions-9',
    source: 1530,
  },
  'שבי שומרון': {
    he: 'שבי שומרון',
    geolexid: '540037',
    en: 'Shavei Shomron',
    checkboxRegions: 'checkboxRegions-9',
    source: 1411,
  },
  שקד: {
    he: 'שקד',
    geolexid: '540040',
    en: 'Shaked',
    checkboxRegions: 'checkboxRegions-9',
    source: 1477,
  },
  'נווה זוהר': {
    he: 'נווה זוהר',
    geolexid: '540064',
    en: 'Neve Zohar',
    checkboxRegions: 'checkboxRegions-5',
    source: 1657,
  },
  ביצרון: {
    he: 'ביצרון',
    geolexid: '540070',
    en: 'Bitzaron',
    checkboxRegions: 'checkboxRegions-7',
    source: 817,
  },
  תימורים: {
    he: 'תימורים',
    geolexid: '540071',
    en: 'Timorim',
    checkboxRegions: 'checkboxRegions-5',
    source: 811,
  },
  עיינות: {
    he: 'עיינות',
    geolexid: '540099',
    en: 'Ayanot',
    checkboxRegions: 'checkboxRegions-7',
    source: 807,
  },
  'בית חשמונאי': {
    he: 'בית חשמונאי',
    geolexid: '540101',
    en: 'Beit Hashmonai',
    checkboxRegions: 'checkboxRegions-2',
    source: 907,
  },
  גינתון: {
    he: 'גינתון',
    geolexid: '540105',
    en: 'Ginaton',
    checkboxRegions: 'checkboxRegions-1',
    source: 760,
  },
  'כפר קאסם': {
    he: 'כפר קאסם',
    geolexid: '540110',
    en: 'Kfar Qasim',
    checkboxRegions: 'checkboxRegions-4',
    source: 636,
  },
  'נווה ירק': {
    he: 'נווה ירק',
    geolexid: '540112',
    en: 'Neve Yarak',
    checkboxRegions: 'checkboxRegions-4',
    source: 662,
  },
  'נווה ימין': {
    he: 'נווה ימין',
    geolexid: '540113',
    en: 'Neve Yamin',
    checkboxRegions: 'checkboxRegions-4',
    source: 642,
  },
  אייל: {
    he: 'אייל',
    geolexid: '540120',
    en: 'Eyal',
    checkboxRegions: 'checkboxRegions-6',
    source: 47,
  },
  'בית ברל': {
    he: 'בית ברל',
    geolexid: '540124',
    en: 'Beit Berl',
    checkboxRegions: 'checkboxRegions-4',
    source: 674,
  },
  טייבה: {
    he: 'טייבה',
    geolexid: '540125',
    en: 'Tayibe',
    checkboxRegions: 'checkboxRegions-4',
    source: 705,
  },
  קלנסווה: {
    he: 'קלנסווה',
    geolexid: '540126',
    en: 'Qalansawe',
    checkboxRegions: 'checkboxRegions-4',
    source: 637,
  },
  עולש: {
    he: 'עולש',
    geolexid: '540133',
    en: 'Olesh',
    checkboxRegions: 'checkboxRegions-4',
    source: 650,
  },
  'ניצני עוז': {
    he: 'ניצני עוז',
    geolexid: '540134',
    en: 'Nitzanei Oz',
    checkboxRegions: 'checkboxRegions-4',
    source: 661,
  },
  גאולים: {
    he: 'גאולים',
    geolexid: '540139',
    en: 'Geulim',
    checkboxRegions: 'checkboxRegions-4',
    source: 618,
  },
  העוגן: {
    he: 'העוגן',
    geolexid: '540140',
    en: 'HaOgen',
    checkboxRegions: 'checkboxRegions-4',
    source: 627,
  },
  'פרדס חנה כרכור': {
    he: 'פרדס חנה כרכור',
    geolexid: '540146',
    en: 'Pardes Hanna Karkur',
    checkboxRegions: 'checkboxRegions-6',
    source: 719,
  },
  'בית אורן': {
    he: 'בית אורן',
    geolexid: '540159',
    en: 'Beit Oren',
    checkboxRegions: 'checkboxRegions-6',
    source: 507,
  },
  עראבה: {
    he: 'עראבה',
    geolexid: '540187',
    en: 'Arraba',
    checkboxRegions: 'checkboxRegions-6',
    source: 196,
  },
  'כפר יאסיף': {
    he: 'כפר יאסיף',
    geolexid: '540194',
    en: 'Kafr Yasif',
    checkboxRegions: 'checkboxRegions-6',
    source: 177,
  },
  'בוסתן הגליל': {
    he: 'בוסתן הגליל',
    geolexid: '540210',
    en: 'Bustan HaGalil',
    checkboxRegions: 'checkboxRegions-6',
    source: 207,
  },
  גורן: {
    he: 'גורן',
    geolexid: '540215',
    en: 'Goren',
    checkboxRegions: 'checkboxRegions-6',
    source: 239,
  },
  'מגדל תפן': {
    he: 'מגדל תפן',
    geolexid: '540222',
    en: 'The Tefen Tower',
    checkboxRegions: 'checkboxRegions-6',
    source: 375,
  },
  'מעלה גלבוע': {
    he: 'מעלה גלבוע',
    geolexid: '540245',
    en: 'Maale Gilboa',
    checkboxRegions: 'checkboxRegions-6',
    source: 477,
  },
  'מסילת ציון': {
    he: 'מסילת ציון',
    geolexid: '540282',
    en: 'Mesilat Zion',
    checkboxRegions: 'checkboxRegions-2',
    source: 972,
  },
  'מוצא עילית': {
    he: 'מוצא עילית',
    geolexid: '540286',
    en: 'Motza Illit',
    checkboxRegions: 'checkboxRegions-2',
    source: 1018,
  },
  'פארק מדע ותעשייה מבוא כרמל': {
    he: 'פארק מדע ותעשייה מבוא כרמל',
    geolexid: '547970',
    en: 'Mevo Carmel Science and Industry Park',
    checkboxRegions: 'checkboxRegions-6',
    source: 1994,
  },
};
