version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

    env_file:
      - ./.env
   

  jobs-agent:
    environment:
      NODE_ENV: production
    container_name: jobs-agent-pro

    image: romorlovich/jobs-agent-backend
    ports:
         - 5000:5000

    depends_on:
      -  rabbitmq
    env_file:
      - ./.env
      



