version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

    env_file:
      - ./.env
   

  jobs-agent:
    environment:
      NODE_ENV: production
    build:
         context: .
         dockerfile: Dockerfile
    ports:
         - 5000:5000

    depends_on:
      -  rabbitmq
    env_file:
      - ./.env
      



