version: '3.8'

services:
  rabbitmq:
    build: ./rabbitMQ
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 10s
      retries: 3

    env_file:
      - ./.env
   

  jobs-agent:
    container_name: jobs-agent-dev

    environment:
      NODE_ENV: development
      
    build:
       context: .
       dockerfile: ./src/Dockerfile.dev
    image: jobs-agent-dev
    

    ports:
         - 5000:5000
    volumes:
      -  ./:/app/

    restart: on-failure
    depends_on:
        rabbitmq:
           condition: service_healthy
    env_file:
      - ./.env
      



volumes:

   jobs-agent:
      driver:
         local