export const MESSAGE_CODES = {
  SCANNER_SUCCESS: '1000',
  ENTER_VALID_QUERY: '1001',
  SEARCH_IS_IN_PROCESS: '1002',
  JOBS_ARE_NOT_FOUND: '1003',
  URL_QUERY_NOT_VALID: '1004',
  USER_IS_FOUND: '2000',
  USER_NOT_FOUND: '2001',
  USER_ID_NOT_VALID: '2002',
  USER_IS_UPDATED: '2003',
  USER_QUERY_DELETED: '2004',
  USER_QUERY_NOT_FOUND: '2005',
  USER_PROFILE_FORM_POSITION_IS_NOT_VALID: '2006',
  USER_PROFILE_FORM_LOCATION_IS_NOT_VALID: '2007',
  FOUNDED: '8000',
  FOUNDED_BUT_NOT_MODIFIED: '8001',
  SOMETHING_WRONG: '10000',
} as const;

export type MessageCodeType = typeof MESSAGE_CODES;
export type MessageCodeKeys = keyof MessageCodeType;
export const getMessageCode = (keyCode: MessageCodeKeys) => MESSAGE_CODES[keyCode];
